version: '3.6'
services:

  # TODO(iwaltgen): minio, drone, (registry s3 적용?) 으로 수정하자.
  registry:
    restart: always
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - ./data/registry:/var/lib/registry
    network_mode: host

  registry-web:
    restart: always
    image: snagles/docker-registry-manager
    environment:
      - MANAGER_PORT=5001
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
    volumes:
      - ./registries.yml:/app/registries.yml
    depends_on:
      - registry
    network_mode: host

  portainer:
    restart: always
    image: portainer/portainer
    command: ["-p", ":80", "-H", "unix:///var/run/docker.sock", "--admin-password", "$$2y$$12$$AydHBnAs7lqSxpI3LenOdeoeqWi4WfEIn4U6WJBOqUDSxiVA8ls7a"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    network_mode: host

  jenkins:
    restart: always
    image: iwaltgen/jenkins-dind
    privileged: true
    environment:
      - JENKINS_OPTS=--httpPort=5050 --httpsPort=5051
      - TRY_UPGRADE_IF_NO_MARKER=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/jenkins:/var/jenkins_home
    network_mode: host

  netdata:
    image: netdata/netdata
    hostname: docker.keecon.com
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
