version: '3'

services:

  mantisbt:
    image: iwaltgen/mantisbt
    ports:
      - 8989:80
    links:
      - postgres
    volumes:
      - ./data/mantis/config:/var/lib/www/html/config
      - ./data/mantis/custom:/var/lib/www/html/custom
    restart: always

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=bugtracker
      - POSTGRES_USER=mantisbt
      - POSTGRES_PASSWORD=mantisbt
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
