name: build

on:
  push:
    branches:
    - master

jobs:
  cgo-mingw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build cgo-mingw
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/cgo-mingw
          registry: ghcr.io
          tag: latest
          dockerfile: cgo-mingw/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  golang-dind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build golang-dind
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/golang-dind
          registry: ghcr.io
          tag: latest
          dockerfile: golang-dind/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  jdk11-dind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build jdk11-dind
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/jdk11-dind
          registry: ghcr.io
          tag: latest
          dockerfile: jdk11-dind/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  minio-mc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build minio/mc
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/minio/mc
          registry: ghcr.io
          tag: latest
          dockerfile: minio/mc/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  jenkins-dind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build jenkins-dind
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/jenkins-dind
          registry: ghcr.io
          tag: latest
          dockerfile: jenkins-dind/Dockerfile
          directory: jenkins-dind
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  prototool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build prototool
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: iwaltgen/prototool
          registry: ghcr.io
          tag: latest
          dockerfile: prototool/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
